### ISSUE TITLE
Provide 'env' as option like child_process.exec

### ISSUE THREAD

**Issue by michaeljones** [otiai10/lookpath#102]
Child process `exec` allows you to override the execution environment. We're doing that at the moment and so find ourselves in a situation where we want to answer the question "Given this environment, can program 'x' be found?". 

This module currently looks at `process.env` directly. I'm wondering if it is possible to add an `env` option and check that or `process.env` if the option is undefined, like [exec](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) does (I think).

I'm not sure that I'm going to end up using this module so this is only a thought which I thought I'd share. 

Thanks for making the project. It does look useful and it is good to know that it follows an approach already tried and tested with Go.

**Comment by otiai10** [comment]
Thank you for your feedback.
Can `include` option solve your problem?

```js
const yourAdditionalPathOrWhatYourAdditionalEnvHas = ["/foo/baa/baz", "/hoge/fuga/piyo"];
const p = await lookpath("echo", {include: yourAdditionalPathOrWhatYourAdditionalEnvHas});
```

If you are talking about `env.PathExt` of Windows or you just want to merge everything in your additional env, your point make sense and I would add something like below:

```js
const opt = {env: yourenv};
const p = await lookpath("echo", opt);
```

which means `env` field for [`LookpathOption`](https://github.com/otiai10/lookpath/blob/main/src/index.ts#L71-L82).

Let me know your thought. @michaeljones

**Comment by michaeljones** [comment]
Thank you for such a quick reply.

I am thinking something like the second option you have there. 

I want to be able to say "completely ignore the current `process.env` and work from this `env` object instead". It might be possible to achieve that with `include` and `exclude` but only by diffing the two PATHs on the two different envs and doing some careful work. An `env` option in the `LookpathOption` feels natural to me as it mirrors the `child_process.exec` behaviour but I realise what might feel natural to me might not be inline with your expectations for the project.

**Comment by otiai10** [comment]
Thank you,
To sum up the discussion:
* When users want to "merge" or "reduce" PATH, use `include` or `exclude`
* When users want to "replace" PATH or other any env, use `env`

That's my view now ;)

**Comment by michaeljones** [comment]
Yeah, I think that sounds reasonable. Thanks for summarising :) 

Again, I don't want you to feel any pressure to include this. We've ended up just trying to execute commands we also want their version information back. But if you think this feature is a good fit then it might makes sense to include it.
