### ISSUE TITLE
Not working in WSL

### ISSUE THREAD

**Issue by Kanna727** [otiai10/lookpath#11]
### Description

lookpath is searching for path in /mnt folder, which is nothing but Windows drives mounted to WSL Linux.
Thus even though Ruby is not installed in WSL Linux, lookpath is finding the path from Windows installation of Ruby
Even if Ruby is installed in WSL Linux, lookpath is returning path from Windows installation of Ruby.

**Comment by otiai10** [comment]
From your PR, as I understand it, `/mnt` is listed inside `Path` variable.
Then, why its inside `Path`? Is there any reason?

IMO, the cause of this problem is that `/mnt` is in `Path` of WSL.

What do you think.

**Comment by Kanna727** [comment]
I have no idea why `/mnt` is inside `Path`. May be it exists by default in WSL. So it's better to exclude `/mnt` from the directories list even if it is in `Path` or not

**Comment by otiai10** [comment]
@Kanna727 
This is my idea. Please check it out https://github.com/otiai10/lookpath/commit/318682e39f27d78dab8898e850d0453a5c96c313

**Comment by Kanna727** [comment]
@otiai10 looks good. Thanks for the fix
