### ISSUE TITLE
Error: Cannot find module 'lib/index.js'

### ISSUE THREAD

**Issue by foooomio** [otiai10/lookpath#3]
In package.json `"main": "./lib/index.js"`, but `lib/` is not published in npm repository.

**Comment by otiai10** [comment]
Thanks. Could you try v1.0.3 just released

```
npm notice
npm notice 📦  lookpath@1.0.3
npm notice === Tarball Contents ===
npm notice 1.3kB package.json
npm notice 222B  .eslintrc.js
npm notice 1.1kB LICENSE
npm notice 1.6kB README.md
npm notice 260B  bin/lookpath.js
npm notice 636B  lib/index.d.ts
npm notice 8.0kB lib/index.js
npm notice 4.2kB src/index.ts
npm notice === Tarball Details ===
npm notice name:          lookpath
npm notice version:       1.0.3
npm notice package size:  5.4 kB
npm notice unpacked size: 17.2 kB
npm notice shasum:        1486c94e9c8052ffa531ef90e8e72c80d7f1dfe4
npm notice integrity:     sha512-XIdgzlX26g10X[...]OPegWc+CsxYMg==
npm notice total files:   8
npm notice
+ lookpath@1.0.3
```

**Comment by foooomio** [comment]
Sorry, this is not the problem of this package.

I noticed that lookpath@1.0.2 actually has lib/ directory, but too.js still uses lookpath@0.1.1. Could you please upgrade dependency of too.js?

**Comment by otiai10** [comment]
ｱｰﾊﾝ

**Comment by otiai10** [comment]
Just update `too.js` as 2.0.3

**Comment by foooomio** [comment]
Thanks! It works!! I'm sorry to trouble you.

**Comment by otiai10** [comment]
You don't need to be sorry but could you please upvote this answer for me 🤪
https://stackoverflow.com/questions/34953168/node-check-existence-of-command-in-path/56321089#56321089

**Comment by foooomio** [comment]
Upvoted. But it seems to have no effect because my reputation is little...
https://stackoverflow.com/help/whats-reputation
