### ISSUE TITLE
lookpath not working in Windows in some situations

### ISSUE THREAD

**Issue by edwin0cheng** [otiai10/lookpath#4]
For example, if my Path environment variable contains `C:\Users\Edwin\.cargo\bin` and this directory contains :
```
cargo.exe
ra_lsp_server.exe
```

In https://github.com/otiai10/lookpath/blob/a0da948a0cd3e78af2e132e427e2bae2aee3e287/src/index.ts#L65

The contents of `matches` will be 
```
C:\Users\Edwin\.cargo\bin\ra_lsp_server.exe
````

However in https://github.com/otiai10/lookpath/blob/a0da948a0cd3e78af2e132e427e2bae2aee3e287/src/index.ts#L43

It will append `ext` to it, so it will became
```
C:\Users\Edwin\.cargo\bin\ra_lsp_server.exe.exe
```
Such that the access test will fail

**Comment by otiai10** [comment]
ah, gotcha. thx

**Comment by otiai10** [comment]
#5

**Comment by edwin0cheng** [comment]
Just checked, it works now, thank you!
