### ISSUE TITLE
Doesn't find filenames with extension on Windows

### ISSUE THREAD

**Issue by matangover** [otiai10/lookpath#45]
For example, `lookpath('ping.exe')` should succeed.

**Comment by otiai10** [comment]
Thank you, @matangover.
Let me clarify just a bit more.

* Given you have `ping.exe` anywhere in your `Path`
* When you try `lookpath('ping.exe')`
* Expect it returns the absolute path to `ping.exe`
* Unexpectedly you get `undefined`

Is it right?

**Comment by matangover** [comment]
Exactly :) and it seems that other similar tools do find it: Go's lookpath, Windows `where` command, Python's `shutil.which`.

**Comment by otiai10** [comment]
@otiai10 

Reproduced
![image](https://user-images.githubusercontent.com/931554/108803867-1e36d980-75df-11eb-84b5-4c5947e3603b.png)

**Comment by otiai10** [comment]
I added some test cases and it works as expected on branch `develop`.
https://github.com/otiai10/lookpath/pull/50/files

Could you try this branch on your environment and share the result?

**Comment by matangover** [comment]
Excellent. It works, I just tested it. Thank you very much!
